name: FTP Deploy zu Domaintechnik

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code von GitHub holen
        uses: actions/checkout@v4

      - name: Dateien per FTP übertragen
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./www/
          # Zwinge den Roboter in den passiven Modus:
          protocol: ftp
          port: 21
