name: Scan Unsplash Bilder

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Python vorbereiten
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Requests installieren
        run: pip install requests

      - name: Python Scan starten
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python py-data/find_unsplash.py

      - name: Credits JSON speichern
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add py-data/unsplash_credits.json

          git commit -m "Update Unsplash Credits" || echo "Keine Änderungen"

          git push