name: Scan Unsplash Bilder

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Python vorbereiten
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Requests installieren
        run: pip install requests

      - name: Python Scan starten
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python py-data/find_unsplash.py